### ISSUE TITLE
Criar M.E.R.

### ISSUE THREAD

**Issue by Alvaro590** [safiratec/safiratec.documentation#5]

**Comment by H3l104UGUST0** [comment]
![WhatsApp Image 2022-11-28 at 13 36 44](https://user-images.githubusercontent.com/100459319/206944839-32f63dd8-a430-4308-9af4-10c14b434ac6.jpeg)

**Comment by H3lio4ugusto** [comment]
![modeloER](https://user-images.githubusercontent.com/100459319/207500290-c8f18bd7-7475-4323-adbd-f9db6bf25c98.jpg)
